src/FinanceBundle/Entity/Item.php
<?php

namespace FinanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * @ORM\Table(name="item")
 * @ORM\Entity(repositoryClass="FinanceBundle\Repository\ItemRepository")
 * @ORM\Cache("NONSTRICT_READ_WRITE")
 */
class Item
{
    use ItemOperations;
    use ORMBehaviors\Translatable\Translatable;

    // Types
    public const TYPE_COMPANY = 0;
    public const TYPE_BANK = 1;
    public const TYPE_MERCHANT = 2;
    public const TYPE_SCOTLAND_LP_CHILD = 3;
    public const TYPE_SPECIAL_OFFERS = 4;

    // Buy status
    public const AVAILABLE = 1;
    public const ITEM_SOLD = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @var int
     *
     * @ORM\Column(name="charterCapital", type="integer", nullable=true)
     */
    private $charterCapital;

    /**
     * @var array
     */
    private $childItems = [];

    /**
     * @var bool
     */
    private $isDist = 1;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->translate()->getName();
    }

    /**
     * Get country.
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set country.
     *
     * @param string $country
     *
     * @return Item
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->translate()->getDescription();
    }

    /**
     * @return int
     */
    public function getCharterCapital()
    {
        return $this->charterCapital;
    }

    /**
     * @param int $charterCapital
     *
     * @return $this
     */
    public function setCharterCapital($charterCapital)
    {
        $this->charterCapital = $charterCapital;

        return $this;
    }

    /**
     * @return array
     */
    public function getChildItems(): array
    {
        return $this->childItems;
    }

    /**
     * @param Item $childItem
     *
     * @return $this
     */
    public function setChildItem($childItem)
    {
        $this->childItems[] = $childItem;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus(int $status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return bool
     */
    public function isDist(): bool
    {
        return $this->isDist;
    }

    /**
     * @param bool $isDist
     * @return $this
     */
    public function setIsDist(bool $isDist)
    {
        $this->isDist = $isDist;

        return $this;
    }

    /**
     * @return bool
     */
    public function isBankItem()
    {
        return $this->getType() === self::TYPE_BANK;
    }
}

src/FinanceBundle/Controller/CheckoutController.php
<?php

namespace FinanceBundle\Controller;

use FinanceBundle\Entity\Order;
use Symfony\Component\HttpFoundation\Request;

class CheckoutController extends AbstractController
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function cartAction()
    {
        $data = $this->get('finance.cart.items')->getItemsFromSession();

        return $this->render(
            '@Finance/Checkout/cart.html.twig',
            [
                'items' => $data['items'],
                'sum' => $data['costSum'],
            ]
        );
    }

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function userDetailsAction(Request $request)
    {
        $data = $this->get('finance.cart.items')->getItemsFromSession();

        if (empty($data['items'])) {
            return $this->redirectToRoute('finance_user_cart');
        }

        $order = new Order();
        $form = $this->createForm('FinanceBundle\Form\Type\OrderType', $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order = $this->get('finance.order')->createOrder($data['items'], $order);
            $request->getSession()->set('orderId', $order->getId());
            $this->get('logger')->addInfo('New order created', [$order]);
            if ($order->getPayment() === 1) {
                return $this->redirectToRoute('finance_mypos');
            }
        }

        return $this->render(
            '@Finance/Checkout/details.html.twig',
            [
                'items' => $data['items'],
                'sum' => $data['costSum'],
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function finalStepAction(Request $request)
    {
        if (!$request->getSession()->has('orderId')) {
            throw $this->createAccessDeniedException();
        }

        /** @var Order $order */
        $order = $this->getRep('FinanceBundle:Order')->findOneById(
            $request->getSession()->get('orderId')
        );

        if (!$order) {
            throw $this->createNotFoundException();
        }

        $order->setStatus(Order::PAYED);
        $this->save($order);

        $response = $this->render(
            '@Finance/Checkout/success.html.twig',
            [
                'order' => $order,
            ]
        );

        if ($this->getUser()) {
            $this->get('finance.mailer')->sendTemplate(
                '@Finance/Emails/order/new.mjml.html.twig',
                [
                    'order' => $order,
                ],
                $this->get('translator')->trans('Ваш заказ').'#'.$order->getId(),
            'moxnrl@gmail.com'
            );
        }

        $this->get('finance.mailer')->sendTemplate(
            '@Finance/Emails/order/manager.mjml.html.twig',
            [
                'order' => $order,
            ],
            'Новый заказ #'.$order->getId(),
            $this->getRep('FinanceBundle:Config')->findOneById(6)->getValue()
        );

        $cart = $this->get('finance.cart');

        $request->getSession()->remove('orderId');
        $response->headers->setCookie($cart->clearCart());

        return $response;
    }

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function cancelAction(Request $request)
    {
        if (!$request->getSession()->has('orderId')) {
            throw $this->createAccessDeniedException();
        }

        /** @var Order $order */
        $order = $this->getRep('FinanceBundle:Order')->findOneById(
            $request->getSession()->get('orderId')
        );

        $order->setStatus(Order::CANCELED);
        $this->save($order);

        return $this->render(
            '@Finance/Checkout/cancel.html.twig'
        );
    }
}

src/FinanceBundle/Resources/views/Checkout/cancel.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}
{% block content %}
    <div class="wrapper store-cart"><h1>{{ 'Корзина' | trans }}</h1>
        <div class="nav-private-office opt2">
            <ul class="list-step">
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Список покупок' | trans }}</span>
                    <span class="list-step__number">1</span>
                </li>
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Оформление заказа' | trans }}</span>
                    <span class="list-step__number">2</span></li>
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Завершение' | trans }}</span>
                    <span class="list-step__number">3</span>
                </li>
            </ul>
        </div>
        <div class="box-form-private-office opt3">
            <div class="text-page long">
                <h2 class="title-terms">{{ 'Оплата отменена' | trans }}</h2>
            </div>
        </div>
    </div>
{% endblock %}

src/FinanceBundle/Resources/views/Checkout/cart.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}
{% block content %}
    <div class="wrapper store-cart"><h1>{{ 'Корзина' | trans }}</h1>
        {% if items | length > 0 %}
            <div class="nav-private-office opt2">
                <ul class="list-step">
                    <li class="active list-step__item">
                        <span class="list-step__title">{{ 'Список покупок' | trans }}</span>
                        <span class="list-step__number">1</span>
                    </li>
                    <li class="list-step__item">
                        <span class="list-step__title">{{ 'Оформление заказа' | trans }}</span>
                        <span class="list-step__number">2</span></li>
                    <li class="list-step__item">
                        <span class="list-step__title">{{ 'Завершение' | trans }}</span>
                        <span class="list-step__number">3</span>
                    </li>
                </ul>
            </div>
            <div class="box-form-private-office opt3">
                <div class="box-history opt2">

                    <ul class="table-history">
                        <li class="tr">
                            <div class="th col3">{{ 'Имя' | trans }}</div>
                            <div class="th col6">{{ 'Стоимость' | trans }}</div>
                            <div class="th col5">{{ 'Удалить' | trans }}</div>
                        </li>
                        {% for item in items %}
                            <li class="tr" id="{{ item.id }}">
                                <div class="td">
                                    <a class="table-history__title" href="#">
                                        {{- item.name -}}
                                    </a>
                                    {% if item.childItems | length > 0 %}
                                        {% for specialItem in item.childItems %}
                                            <span>{{- specialItem.name -}}</span><br/>
                                        {% endfor %}
                                    {% endif %}
                                    {% if item.bankItem %}
                                        {% if item.dist %}
                                            {{- 'Персональное присутствие' | trans -}}
                                        {% else  %}
                                            {{- 'Дистанционное открытие' | trans -}}
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <div class="td">
                                    <p class="table-history__price">&euro; {{ item.cost }}</p>
                                </div>
                                <div class="td">
                                    <a class="remove-from-cart box-history__delete"
                                       data-item-id="{{ item.id }}"
                                       data-item-cost="{{ item.cost }}"
                                       href="">{{ 'Удалить~' | trans }}</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="line-total-form opt2">
                        <p class="line-total-form__price">{{ 'Итого' | trans }} &euro;<span>{{ sum }}</span></p>

                        {% if app.user %}
                            <a class="button button_form size3"
                               href="{{ path('finance_user_details') }}">{{ 'Далее' | trans }}</a>
                        {% else %}
                            <a class="button size2"
                               href="{{ path('finance_user_details') }}">{{ 'Быстрое оформление' | trans }}</a>
                            <a class="button button_form opt3"
                               href="{{ path('finance_login') }}">{{ 'Купить с авторизацией*' | trans }}</a>
                        {% endif %}
                    </div>
                    {% if not app.user %}
                        <p class="box-history__help">
                            * {{ 'Возможность просматривать статус заказа местоположение груза и историю покупок' | trans }}</p>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <div class="box-form-private-office opt3 empty-cart">
                <p>{{ 'Ваша корзина пуста' | trans }}</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    {% javascripts
    '@FinanceBundle/Resources/public/js/cart.js'
    filter='uglifyjs2' %}

    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/FinanceBundle/Resources/views/Checkout/details.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}

{% block stylesheet %}
    {{ parent() }}

    {% stylesheets
    'assets/vendor/intl-tel-input/build/css/intlTelInput.css'
    filter='uglifycss' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>Корзина</h1>
        <div class="nav-private-office opt2">
            <ul class="list-step">
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Список покупок' | trans }}</span>
                    <span class="list-step__number">1</span></li>
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Оформление заказа' | trans }}</span>
                    <span class="list-step__number">2</span>
                </li>
                <li class="list-step__item">
                    <span class="list-step__title">{{ 'Завершение' | trans }}</span>
                    <span class="list-step__number">3</span>
                </li>
            </ul>
        </div>
        <div class="box-form-private-office opt2">
            {{ form_start(form, {'attr': {'id': 'order-form'}}) }}
            <div class="form-basket__column">
                <h3>{{ 'Личные данные' | trans }}</h3>
                <div class="line-fields">
                    {%- if form_errors(form.firstName) -%}
                        <div class="worning-form long">
                            <p>{{ form_errors(form.firstName) }}</p>
                        </div>
                    {%- endif -%}
                    <div class="box-field w50">
                        <label>{{ 'Имя' | trans }}</label>
                        <div class="box-field__input">
                            {{ form_widget(form.firstName, {'attr': {'class': 'standart-input'}, 'value' : app.user ? app.user.firstName : '' }) }}
                        </div>
                    </div>
                    {%- if form_errors(form.lastName) -%}
                        <div class="worning-form long">
                            <p>{{ form_errors(form.lastName) }}</p>
                        </div>
                    {%- endif -%}
                    <div class="box-field w50">
                        <label>{{ 'Фамилия' | trans }}</label>
                        <div class="box-field__input">
                            {{ form_widget(form.lastName, {'attr': {'class': 'standart-input' }, 'value' : app.user ? app.user.lastName : '' }) }}
                        </div>
                    </div>
                </div>
                <div class="line-fields {{ app.user ? 'hidden' : '' }}">
                    {%- if form_errors(form.email) -%}
                        <div class="worning-form long">
                            <p>{{ form_errors(form.email) }}</p>
                        </div>
                    {%- endif -%}
                    <div class="box-field w50">
                        <label>{{ 'Адрес электронной почты' | trans }}</label>
                        <div class="box-field__input">
                            {{ form_widget(form.email, {'attr': {'class': 'standart-input'}, 'value' : app.user ? app.user.email : '' }) }}
                        </div>
                    </div>
                </div>
                <div class="line-fields">
                    {%- if form_errors(form.country) -%}
                        <div class="worning-form long">
                            <p>{{ form_errors(form.country) }}</p>
                        </div>
                    {%- endif -%}
                    <div class="box-field w50">
                        <label>{{ 'Страна' | trans }}</label>
                        <div class="box-field__input">
                            {{ form_widget(form.country, {'attr': {'class': 'standart-input'}}) }}
                        </div>
                    </div>
                    {%- if form_errors(form.city) -%}
                        <div class="worning-form long">
                            <p>{{ form_errors(form.city) }}</p>
                        </div>
                    {%- endif -%}
                    <div class="box-field w50">
                        <label>{{ 'Город' | trans }}</label>
                        <div class="box-field__input">
                            {{ form_widget(form.city, {'attr': {'class': 'standart-input' }}) }}
                        </div>
                    </div>
                </div>
                {%- if form_errors(form.street) -%}
                    <div class="worning-form long">
                        <p>{{ form_errors(form.street) }}</p>
                    </div>
                {%- endif -%}
                <div class="box-field">
                    <label>{{ 'Улица' | trans }}</label>
                    <div class="box-field__input">
                        {{ form_widget(form.street, {'attr': {'class': 'standart-input'}}) }}
                    </div>
                </div>
                {%- if form_errors(form.phone) -%}
                    <div class="worning-form long">
                        <p>{{ form_errors(form.phone) }}</p>
                    </div>
                {%- endif -%}
                <div class="box-field">
                    <label>{{ 'Номер телефона' | trans }}</label>
                    <div class="box-field__input">
                        {{ form_widget(form.phone, {'attr': {'class': 'standart-input'}, 'value' : app.user ? '+' ~ app.user.phone : '' }) }}
                    </div>
                </div>
                {%- if form_errors(form.zip) -%}
                    <div class="worning-form long">
                        <p>{{ form_errors(form.zip) }}</p>
                    </div>
                {%- endif -%}
                <div class="box-field">
                    <label>{{ 'Индекс' | trans }}</label>
                    <div class="box-field__input">
                        {{ form_widget(form.zip, {'attr': {'class': 'standart-input'}}) }}
                    </div>
                </div>
                {%- if form_errors(form.payment) -%}
                    <div class="worning-form long">
                        <p>{{ form_errors(form.payment) }}</p>
                    </div>
                {%- endif -%}
                <ul class="list-radio for-payment">
                    <li class="list-radio__item">
                        {{ form_widget(form.payment[0], {'attr': {'class': 'hidden'}, 'label': ' '}) }}
                        {{ form_widget(form.payment[1], {'attr': {'class': 'js-styled'}, 'label': ' '}) }}
                        <label for="order_payment_1">
                                <span class="list-radio__icon">
                                    <img src="{{ asset('/img/master-card-logo.png') }}" alt="" width="55"/>
                                    <img src="{{ asset('/img/visa-logo.png') }}" alt="" width="45"/>
                                    <img src="{{ asset('/img/unionpay-logo.png') }}" alt="" width="60"/>
                                </span>
                        </label>
                    </li>
                </ul>

                <div class="box-field popup-list rules-list">
                    <div class="box-field__input">
                        <input class="checkbox_popup styled"
                               type="checkbox"
                               name="_remember_me"
                               id="remember_me_field"
                               required="required">
                        <label for="remember_me_field">
                            {{- 'Я согласен с' | trans }}
                            <a href="{{ path('finance_page', {'link':  'documents/terms-of-business' }) }}"
                               target="_blank">{{ 'Коммерческими Условиями' | trans }}</a> {{ 'и' | trans }}
                            <a href="{{ path('finance_page', {'link':  'documents/refund-policy' }) }}"
                               target="_blank">{{ 'Политикой Возврата' | trans }}</a>
                        </label>
                    </div>
                </div>
                {{ form_widget(form.status, {'attr': {'class': 'hidden'}}) }}
                {{ form_rest(form) }}
            </div>

            <div class="line-total-form">
                <p class="line-total-form__price">
                    {{- 'Итого' | trans }}<span>&euro; {{ sum }}</span>
                </p>
                <a class="button button_form button_gray"
                   href="{{ path('finance_user_cart') }}">
                    {{- 'Cancel' | trans -}}
                </a>
                <input class="button button_form next" type="submit" value="{{ 'Купить' | trans }}">
            </div>
        </div>
        {{ form_end(form) }}
    </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    {% include 'FinanceBundle:Partials:validation-translation.html.twig' %}
    {% javascripts
    'assets/vendor/intl-tel-input/build/js/intlTelInput.min.js'
    'assets/vendor/intl-tel-input/build/js/utils.js'
    '@FinanceBundle/Resources/public/js/forms.js'
    '@FinanceBundle/Resources/public/js/checkout-details.js'
    '@FinanceBundle/Resources/public/js/validation/phone-validation.js'
    '@FinanceBundle/Resources/public/js/validation/order-form.js'
    filter='uglifyjs2' %}

    <script src="{{ asset_url }}"></script>

    {% endjavascripts %}
{% endblock %}

src/FinanceBundle/Resources/views/Checkout/success.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}
{% block content %}
    <div class="wrapper store-cart"><h1>{{ 'Корзина' | trans }}</h1>
        <div class="nav-private-office opt2">
            <ul class="list-step">
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Список покупок' | trans }}</span>
                    <span class="list-step__number">1</span>
                </li>
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Оформление заказа' | trans }}</span>
                    <span class="list-step__number">2</span></li>
                <li class="active list-step__item">
                    <span class="list-step__title">{{ 'Завершение' | trans }}</span>
                    <span class="list-step__number">3</span>
                </li>
            </ul>
        </div>
        <div class="box-form-private-office opt3">
            <div class="text-page long">
                <h2 class="title-terms">{{ 'Оплата успешно произведена' | trans }}</h2>
                <p>
                    {{- 'Номер вашего заказа' | trans }} №{{ order.id -}}
                    <br/>
                    {{- 'В течении 40 минут с вами свяжется специалист из нашей компании для уточнения деталей' | trans -}}
                </p>
            </div>
        </div>
    </div>
    <!-- Begin HTML -->


{% endblock %}

{% block javascript %}
    {{ parent() }}

    <script>
        ga('require', 'ecommerce');
        ga('ecommerce:addTransaction', {
            'id': '{{ order.id }}',
            'affiliation': 'FinFinance',
            'revenue': '{{ order.sum }}',
            'shipping': '0',
            'tax': '0',
            'currency': 'EUR'
        });

        {% for item in order.items %}
        {% if item.parent == null %}
        ga('ecommerce:addItem', {
            'id': '{{ order.id }}',
            'name': '{{ item.name }}',
            'sku': '{{ item.id }}',
            'price': '{{ item.cost }}',
            'quantity': '1'
        });
        {% endif %}
        {% endfor %}

        ga('ecommerce:send');
    </script>
{% endblock %}