src/FinanceBundle/Entity/Page.php
<?php

namespace FinanceBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Page.
 *
 * @ORM\Table(name="page")
 * @ORM\Entity(repositoryClass="FinanceBundle\Repository\PageRepository")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 * @ORM\Cache("NONSTRICT_READ_WRITE")
 */
class Page
{
    use ORMBehaviors\Translatable\Translatable;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="link", type="string", length=255, unique=true)
     */
    private $link;

    /**
     * @Vich\UploadableField(mapping="page_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $created;

    public function __construct()
    {
        $this->translations = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps()
    {
        $this->updatedAt = new \DateTime();

        if ($this->created === null) {
            $this->created = new \DateTime();
        }
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get link.
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set link.
     *
     * @param string $link
     *
     * @return Page
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->translate()->getTitle();
    }

    /**
     * @return string
     */
    public function getText()
    {
        return $this->translate()->getText();
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param \DateTime $created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return $this
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            $this->updatedAt = new \DateTime();
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @param string $imageName
     *
     * @return $this
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/FinanceBundle/Controller/Admin/DefaultController.php
<?php

namespace FinanceBundle\Controller\Admin;

use FinanceBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * Admin index page.
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        return $this->render('FinanceBundle:Admin:index.html.twig');
    }
}

src/FinanceBundle/Controller/DefaultController.php
<?php

namespace FinanceBundle\Controller;

use FinanceBundle\Entity\Item;

class DefaultController extends AbstractController
{
    public function indexAction()
    {
        $merchant = $this->getRep('FinanceBundle:Item')->findMinCostByType(Item::TYPE_MERCHANT);
        $company = $this->getRep('FinanceBundle:Item')->findMinCostByType(Item::TYPE_COMPANY);
        $bank = $this->getRep('FinanceBundle:Item')->findMinCostByType(Item::TYPE_BANK);
        $special = $this->getRep('FinanceBundle:Item')->findMinCostByType(Item::TYPE_SPECIAL_OFFERS);

        return $this->render(
            'FinanceBundle:Default:index.html.twig',
            [
                'merchant' => $merchant,
                'company' => $company,
                'special' => $special,
                'bank' => $bank,
            ]
        );
    }
}

src/FinanceBundle/Resources/views/Default/index.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}

{% block content %}
    <div class="content">
        <div class="wrapper"><h1>{{- 'Платежные институты.' | trans -}}
                <br>{{- 'Готовые компании. Банковские счета.' | trans -}}</h1>
            <div class="box-grid box-grid_main clearfix">
                <div class="box-grid__column column1">
                    <div class="box-grid__item item1 mh2">
                        <div class="box-grid__item-cont"><h3
                                    class="box-grid__title">{{- 'Специальные предложения' | trans -}}</h3>
                            <p class="box-grid__text">{{- 'Специальные предложения' | trans -}}
                                <br>{{- 'включают в себя пакет основных' | trans }} {{ 'услуг и ряд дополнительных сервисов' | trans -}}
                            </p>
                            <div class="box-grid__line-ptice"><p class="box-grid__price">{{- 'от' | trans -}}
                                    &nbsp;&euro;{{ special.cost }}</p><a
                                        class="button white"
                                        href="{{ path('finance_page', {'link':  'special-offers' }) }}">{{- 'Подробнее' | trans -}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-grid__column two-col">
                    <div class="box-grid__column col50 top">
                        <div class="box-grid__item item2 mh1">
                            <div class="box-grid__item-cont">
                                <h3 class="box-grid__title">{{- 'Лицензии Payment Service' | trans -}}
                                    <br>{{- 'Provider (PSP)' | trans -}}</h3>
                                <div class="box-grid__line-ptice"><p class="box-grid__price">{{- 'от' | trans -}}
                                        &nbsp€30000</p><a
                                            class="button white"
                                            href="{{ path('finance_page', {'link':  'license/payment-service-provider' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid__column col100 col100_hide">
                        <div class="box-grid__item item4 mh1">
                            <div class="box-grid__item-cont"><h3
                                        class="box-grid__title">{{- 'Готовые компании' | trans -}}
                                    <br>{{- 'Английское LLP с двумя оффшорными партнерами' | trans -}}</h3>
                                <div class="box-grid__line-ptice"><p class="box-grid__price">{{- 'от' | trans -}}
                                        &nbsp;&euro;{{ company.cost }}</p><a
                                            class="button white"
                                            href="{{ path('finance_page', {'link':  'our-services/offshore-companies' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid__column col50 top">
                        <div class="box-grid__item item3 mh1 white item3_with-img1">
                            <div class="box-grid__item-cont"><h3
                                        class="box-grid__title">{{- 'Банковский счет' | trans -}}</h3>
                                <p class="box-grid__text">{{- 'Открытие банковского счета в Европе' | trans -}}</p>
                                <div class="box-grid__line-ptice top"><p
                                            class="box-grid__price box-grid__price1000">{{- 'от' | trans -}}
                                        &nbsp;&euro;{{ bank.cost }}</p>
                                    <a class="button"
                                       href="{{ path('finance_page', {'link':  'our-services/bank-account' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid__column col100 col100_hide-mob">
                        <div class="box-grid__item item4 mh1">
                            <div class="box-grid__item-cont">
                                <h3 class="box-grid__title">{{- 'Готовые компании' | trans -}}
                                    <br>{{- 'Английское LLP с двумя оффшорными партнерами' | trans -}}
                                </h3>
                                <div class="box-grid__line-ptice"><p class="box-grid__price">{{- 'от' | trans -}}
                                        &nbsp;&euro;{{ company.cost }}</p><a
                                            class="button white"
                                            href="{{ path('finance_page', {'link':  'our-services/offshore-companies' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid__column col50 bottom">
                        <div class="box-grid__item item3 white">
                            <div class="box-grid__item-cont"><h3
                                        class="box-grid__title">{{- 'Мерчант аккаунт' | trans -}}</h3>
                                <p class="box-grid__text">{{- 'Открытие мерчант аккаунт для карт VISA MasterCard American Express' | trans -}}</p>
                                <div class="box-grid__line-ptice"><p class="box-grid__price">{{- 'от' | trans -}}
                                        &nbsp;&euro;{{ merchant.cost }}</p><a
                                            class="button"
                                            href="{{ path('finance_page', {'link':  'our-services/merchant-account' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid__column col50 bottom">
                        <div class="box-grid__item item3 white">
                            <div class="box-grid__item-cont"><h3
                                        class="box-grid__title">{{- 'Выпуск карт' | trans -}}</h3>
                                <p class="box-grid__text">{{- 'Помощь в выпуске банковских' | trans -}}
                                    <br>{{- 'карт MasterCard и VISA' | trans -}}</p>
                                <div class="box-grid__line-ptice box-grid__line-ptice_mod"><a class="button"
                                                                                              href="{{ path('finance_page', {'link':  'our-services/card-issue' }) }}">{{- 'Подробнее' | trans -}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/FinanceBundle/Resources/views/Default/page.html.twig
{% extends 'FinanceBundle::layout.html.twig' %}
{% block title %}{% if page.title %}{{- page.title | striptags }}{% endif %}{% endblock %}
{% block content %}
    <div class="content">
        <div class="wrapper">
            {% if page.title %}
                <h1>{{ page.title | raw }}</h1>
            {% endif %}
            {% if page.text %}
                {{ page.text | raw }}
            {% endif %}
        </div>
    </div>
{% endblock %}